SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	flagadmin		BOOLEAN			NOT NULL	DEFAULT false,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);


CREATE TABLE parent (
	IdParent			INT				NOT NULL			GENERATED BY DEFAULT AS IDENTITY,
	IdCompte			INT				NOT NULL,
	Nom					VARCHAR(25)		NOT NULL,
	Prenom 				VARCHAR(25)		NOT NULL,
	Adresse_Postale		VARCHAR(25)		NOT NULL,
	Email				VARCHAR(25)		NOT NULL,
	Telephone			VARCHAR(25)		NOT NULL,
	FOREIGN KEY (IdCompte) REFERENCES Compte (IdCompte) ON DELETE CASCADE,
	PRIMARY KEY (IdParent)
);


CREATE TABLE contrat (
	IdContrat			INT				NOT NULL			GENERATED BY DEFAULT AS IDENTITY,
	IdParent			INT				NOT NULL,
	Nom					VARCHAR(25)		NOT NULL,
	Prenom				VARCHAR(25)		NOT NULL,
	DateNaissance		DATE			NOT NULL,
	Debut				DATE			NOT NULL,
	Fin					DATE			NOT NULL,
	TarifHoraire		DECIMAL			NOT NULL,
	TauxHoraire			DECIMAL			NOT NULL,
	IndemniteEntretient	DECIMAL			NOT NULL,
	IndemniteRepas      DECIMAL         NOT NULL,
	
	FOREIGN KEY (IdParent) REFERENCES parent (IdParent) ON DELETE CASCADE,
	PRIMARY KEY (IdContrat)
);



CREATE TABLE tarif (
	IdTarif			        INT							NOT NULL	GENERATED BY DEFAULT AS IDENTITY,	
	TarifHoraire            DECIMAL                     NOT NULL,
	MinimumJournalier       DECIMAL                     NOT NULL,
	IndemniteRepas          DECIMAL                     NOT NULL,
	
	PRIMARY KEY(IdTarif)
);	
	
CREATE TABLE garde (
	IdGarde			        INT						 NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	IdContrat			    INT				         NOT NULL,
	DateGarde				DATE					 NOT NULL,
	HeureArrivee            TIME                     NOT NULL,
	HeureDepart        	    TIME                     NOT NULL,
	Repas                   INT                  NOT NULL,
	FOREIGN KEY (IdContrat) REFERENCES contrat (IdContrat) ON DELETE CASCADE,
	PRIMARY KEY(IdGarde)
	
);
